version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: pg
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data:
