version: '3.7'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - network
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
